export const api = 'http://192.168.43.146:3000'
export const profile_api = api+'/user'
export const job_api = api+'/job'
export const notification_api = api+'/notification'
export const booking_api = api+'/booking'
